// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqM9qL1Cibm3P8zd4jKJNVobjFkk9o6rE',
    appId: '1:99707618895:web:2c3d019643f017b7a60c3a',
    messagingSenderId: '99707618895',
    projectId: 'todo-application-6c32e',
    authDomain: 'todo-application-6c32e.firebaseapp.com',
    storageBucket: 'todo-application-6c32e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpYOhdm6ZXF8W_ADrxT1RX7B7OS2RSML0',
    appId: '1:99707618895:android:fd6eb103ec8dc7f5a60c3a',
    messagingSenderId: '99707618895',
    projectId: 'todo-application-6c32e',
    storageBucket: 'todo-application-6c32e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8mfgkMW3gQzXKqF1dRHz7qssQ499LkE',
    appId: '1:99707618895:ios:daa64f88e5efd5a6a60c3a',
    messagingSenderId: '99707618895',
    projectId: 'todo-application-6c32e',
    storageBucket: 'todo-application-6c32e.appspot.com',
    iosClientId: '99707618895-760v77gibn2a556d8esa21iqt0kfv7ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk8mfgkMW3gQzXKqF1dRHz7qssQ499LkE',
    appId: '1:99707618895:ios:daa64f88e5efd5a6a60c3a',
    messagingSenderId: '99707618895',
    projectId: 'todo-application-6c32e',
    storageBucket: 'todo-application-6c32e.appspot.com',
    iosClientId: '99707618895-760v77gibn2a556d8esa21iqt0kfv7ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
